/**
 * API error envelope (07_API.md common error codes + contract-level codes).
 */

export const API_ERROR_STATUS: Record<string, number> = {
  MARKETPLACE_LOCKED: 409,
  INSUFFICIENT_BALANCE: 402,
  PURCHASE_EXPIRED: 410,
  ASSIGNMENT_NOT_FOUND: 404,
  BUYBACK_NOT_FOUND: 404,
  REVENGE_BUFF_NOT_FOUND: 404,
  LEDGER_UNBALANCED: 500,
  INVALID_BATCH_STATE: 409,
  RACE_SEED_VERIFICATION_FAILED: 500,
  RACE_SNAPSHOT_VERIFICATION_FAILED: 500,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  // contract-level codes
  NOT_FOUND: 404,
  VALIDATION_FAILED: 400,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  PURCHASE_SESSION_LIMIT: 409,
  PURCHASE_NOT_CANCELLABLE: 409,
  WITHDRAWAL_BELOW_MINIMUM: 400,
  DEPOSIT_ADDRESS_UNAVAILABLE: 503,
  DUAL_APPROVAL_REQUIRED: 403,
  RECOVERY_NOT_FOUND: 404,
  RECOVERY_ALREADY_OPEN: 409,
  // training (Decision 066)
  HORSE_NOT_FOUND: 404,
  NOT_HORSE_OWNER: 403,
  HORSE_NOT_ACTIVE: 409,
  TRAINING_ALREADY_EXISTS: 409,
  RACE_SNAPSHOT_ALREADY_CREATED: 409,
  INVALID_TRAINING_TYPE: 400,
  // wallet linking (Decision 072)
  WALLET_SIGNATURE_INVALID: 400,
  WALLET_ALREADY_LINKED: 409,
  // recovery (Decision 067)
  RECOVERY_ALREADY_APPROVED: 409,
  RECOVERY_REQUIRES_DUAL_APPROVAL: 403,
  INVALID_RECOVERY_STATE: 409,
  // support bonus placement (Decision 074)
  SUPPORT_NOT_YOUR_REFERRAL: 403,
  SUPPORT_ALREADY_PLACED: 409,
  SUPPORT_PARENT_OUT_OF_SCOPE: 400,
  SUPPORT_PLACEMENT_CYCLE: 409,
  // manual marketplace (Decision 076)
  MARKET_ALREADY_LISTED: 409,
  ITEM_NOT_FOUND: 404,
  ITEM_NOT_SELLABLE: 400,
  ITEM_NOT_GIFTABLE: 400,
  ITEM_NOT_OWNED: 404,
  ITEM_DAY_RANGE: 400,
  ITEM_ALREADY_APPLIED: 409,
  ITEM_USAGE_NOT_FOUND: 404,
  GIFT_RECIPIENT_NOT_FOUND: 404,
  GIFT_SELF: 400,
  GIFT_LIMIT: 429,
  MARKET_ACTION_LIMIT: 409,
  // admin user ops (2026-07-09)
  GRANT_NOT_PENDING: 409,
  // AIカスタマーサービス (2026-07-09)
  CS_SEND_FAILED: 502,
  CONTACT_LIMIT: 429,
  MARKET_DAY_RANGE: 400,
  // 売買自動化設定 (Decision 086)
  TRADE_SETTINGS_INVALID: 400,
};

export class ApiError extends Error {
  constructor(
    readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = 'ApiError';
  }

  get status(): number {
    return API_ERROR_STATUS[this.code] ?? 500;
  }
}

export interface ErrorBody {
  error: { code: string; message: string };
}

export function toErrorBody(code: string, message: string): ErrorBody {
  return { error: { code, message } };
}
